// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxsnkbfelqwnbsfxkkbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4c25rYmZlbHF3bmJzZnhra2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTkwOTIsImV4cCI6MjA1ODIzNTA5Mn0.4S1lOyhiZZ6Dy4FlM5rqRjgF5OlSzzc4-7juorj1NPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});